'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import PortalShell from '../ui/PortalShell';
import { complaints } from '../lib/api';
import { EmptyState, InlineNotice, PageIntro, friendlyError, readList } from '../ui/PortalBlocks';
import { PriorityPill, StatusPill, complaintLocation, formatDate } from '../ui/CivicUI';

function WorkDoneForm({ item, onClose, onSaved }) {
  const [note, setNote] = useState(''); const [photo, setPhoto] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const readPhoto = event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(reader.result); reader.readAsDataURL(file); };
  const submit = async event => { event.preventDefault(); if (note.trim().length < 80) return setError('Add at least 80 characters: what you found, what you did and what the photo proves.'); if (!photo) return setError('Add one completion photo before submitting.'); setBusy(true); const result = await complaints.resolve(item.complaint_id || item._id, { speaking_order: note.trim(), resolution_photos: [{ url: photo }], resolution_type: 'fixed' }); setBusy(false); if (result?.success) onSaved(); else setError(friendlyError(result?.error)); };
  return <form className="v-worker-form" onSubmit={submit}><div className="v-field"><label>Completion note <span style={{ color: 'var(--v-muted)', fontWeight: 500 }}>({note.length}/80 minimum)</span></label><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Describe what you found, what was repaired and how the evidence shows the result." /></div><div className="v-field"><label>Completion photo</label><div className="v-upload"><strong>Upload proof from the site</strong><small>One clear photo is required to propose closure.</small><input type="file" accept="image/*" onChange={readPhoto} /></div>{photo && <div className="v-photo-preview"><img src={photo} alt="Completion preview" /></div>}</div>{error && <p className="v-form-error">{error}</p>}<div className="v-form-actions"><button type="button" className="v-button v-button-ghost" onClick={onClose}>Cancel</button><button className="v-button v-button-primary" disabled={busy}>{busy ? 'Submitting…' : 'Submit work done'} <span>→</span></button></div></form>;
}

export default function WorkerPage() {
  const router = useRouter(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null); const [notice, setNotice] = useState('');
  const load = () => { setLoading(true); complaints.officerQueue().then(result => { setItems(readList(result)); setError(result?.error || ''); setLoading(false); }); };
  useEffect(() => { load(); }, []);
  const start = async item => { const result = await complaints.updateStatus(item.complaint_id || item._id, 'IN_PROGRESS', 'Field work started.'); if (result?.success) load(); else setError(friendlyError(result?.error)); };
  return <PortalShell role="worker"><PageIntro eyebrow="MY WORK" title="A focused queue for the field." detail="Start the job, capture proof, and submit a closure proposal for the citizen to verify." action={<button className="v-button v-button-ghost" onClick={load}>↻ Refresh</button>} />{notice && <InlineNotice tone="success">{notice}</InlineNotice>}{error && <p className="v-form-error">{error}</p>}{loading ? <div className="v-loading" style={{ minHeight: 280 }}><div className="v-loading-mark">V</div><p>Loading your queue…</p></div> : items.length ? <div className="v-worker-list">{items.map(item => <article className="v-worker-card" key={item._id || item.complaint_id}><div className="v-worker-top"><div><span className="v-reference">{item.complaint_id}</span><h2>{item.complaint_text || 'Civic issue'}</h2><p>{complaintLocation(item)} · Filed {formatDate(item.createdAt)}</p></div><PriorityPill value={item.priority} /></div><div className="v-worker-bottom"><StatusPill value={item.status} /><span className="v-worker-dept">{item.department_id?.code || 'Civic network'}</span><div className="v-worker-actions">{String(item.status).toUpperCase() === 'ASSIGNED' && <button className="v-button v-button-ghost" onClick={() => start(item)}>Start work</button>}<button className="v-button v-button-primary" onClick={() => setSelected(item)}>Work done <span>→</span></button></div></div>{selected?._id === item._id && <WorkDoneForm item={item} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); setNotice('Work submitted. The citizen can now verify the result.'); load(); }} />}</article>)}</div> : <EmptyState icon="✓" title="Your queue is clear" detail="New assignments will appear here. Completed work stays available in the Completed tab." action={<button className="v-button v-button-ghost" onClick={() => router.push('/worker/completed')}>View completed work</button>} />}</PortalShell>;
}
