'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import PortalShell from '../../ui/PortalShell';
import VoiceIntakePanel from '../../ui/VoiceIntakePanel';
import { complaints } from '../../lib/api';
import { PageIntro, friendlyError } from '../../ui/PortalBlocks';

const categories = [['GARBAGE_NOT_COLLECTED', 'Waste and cleanliness'], ['WATER_LOGGING', 'Water and flooding'], ['ROAD_DAMAGE', 'Roads and footpaths'], ['BLOCKED_SEWAGE', 'Drains and sewage'], ['STREETLIGHT', 'Street lighting'], ['OTHER', 'Something else']];

export default function NewComplaintPage() {
  const router = useRouter();
  const [form, setForm] = useState({ category: 'GARBAGE_NOT_COLLECTED', complaint_text: '', address: '', district: 'central' });
  const [photos, setPhotos] = useState([]); const [coords, setCoords] = useState(null); const [locationStatus, setLocationStatus] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  const onPhotos = event => { const files = Array.from(event.target.files || []).slice(0, 3); Promise.all(files.map(file => new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve({ url: reader.result, name: file.name }); reader.readAsDataURL(file); }))).then(setPhotos); };
  const submit = async event => { event.preventDefault(); setError(''); if (form.complaint_text.trim().length < 12) return setError('Add a little more detail so the right team can act.'); if (!form.address.trim()) return setError('Add the location of the issue.'); setBusy(true); const result = await complaints.file({ complaint_text: form.complaint_text.trim(), category: form.category, media_urls: photos.map(photo => ({ url: photo.url, type: 'photo' })), location: { address: form.address.trim(), area: form.address.trim(), district: form.district, ...(coords ? { coords: { lat: coords.latitude, lng: coords.longitude } } : {}) }, source: 'web' }); setBusy(false); if (result?.success && result.complaint?.complaint_id) router.push(`/citizen/complaints/${result.complaint.complaint_id}`); else setError(friendlyError(result?.error)); };
  const captureLocation = () => { if (!navigator.geolocation) return setLocationStatus('Location is not available in this browser.'); setLocationStatus('Finding your location'); navigator.geolocation.getCurrentPosition(position => { setCoords({ latitude: position.coords.latitude, longitude: position.coords.longitude }); setLocationStatus('Location attached to this complaint.'); }, () => setLocationStatus('Location permission was not granted.')); };
  return <PortalShell role="citizen"><PageIntro eyebrow="NEW COMPLAINT" title="Give the issue a voice." detail="NagarSetu will call you, capture the useful details, and let you review the record before it enters the civic queue." action={<button className="v-button v-button-ghost" onClick={() => router.back()}>Cancel</button>} /><VoiceIntakePanel onConfirmed={complaint => router.push(`/citizen/complaints/${complaint.complaint_id}`)} /><details className="v-manual-fallback"><summary>Use the written form instead</summary><form className="v-form" onSubmit={submit}><div className="v-panel"><div className="v-form-grid"><div className="v-field v-field-full"><label htmlFor="complaint_text">What needs attention?</label><textarea id="complaint_text" name="complaint_text" value={form.complaint_text} onChange={update} placeholder="Describe the issue and what you can see" maxLength={800} /><small>{form.complaint_text.length}/800</small></div><div className="v-field"><label htmlFor="category">Category</label><select id="category" name="category" value={form.category} onChange={update}>{categories.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div className="v-field"><label htmlFor="district">Area</label><select id="district" name="district" value={form.district} onChange={update}><option value="central">Central</option><option value="east">East</option><option value="north">North</option><option value="south">South</option><option value="west">West</option></select></div><div className="v-field v-field-full"><label htmlFor="address">Location</label><input id="address" name="address" value={form.address} onChange={update} placeholder="Street, landmark or neighbourhood" /></div><div className="v-field v-field-full"><label>Location safety check</label><button type="button" className="v-button v-button-ghost" onClick={captureLocation}>{coords ? 'Location attached' : 'Use device location'}</button>{locationStatus && <small>{locationStatus}</small>}</div><div className="v-field v-field-full"><label>Photo evidence <span>(optional)</span></label><div className="v-upload"><strong>Add up to 3 photos</strong><small>Photos help the field team understand the issue.</small><input type="file" accept="image/*" multiple onChange={onPhotos} /></div>{photos.length > 0 && <div className="v-photo-preview">{photos.map(photo => <img src={photo.url} alt={photo.name} key={photo.name} />)}</div>}</div></div></div><div className="v-form-actions"><button type="submit" className="v-button v-button-primary" disabled={busy}>{busy ? 'Submitting' : 'Submit written complaint'}</button></div></form>{error && <p className="v-form-error">{error}</p>}</details></PortalShell>;
}
