'use client';

import { useEffect, useState } from 'react';
import PortalShell from '../../ui/PortalShell';
import { resources } from '../../lib/api';
import { EmptyState, PageIntro, friendlyError, readPeople } from '../../ui/PortalBlocks';

export default function AdminTeamPage() {
  const [people, setPeople] = useState([]); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ name: '', mobile: '', module: 'BOTH', district: 'central', designation: 'Field owner' }); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = () => resources.officers().then(owners => { setPeople(readPeople(owners)); setError(owners?.error || ''); setLoading(false); });
  useEffect(() => { load().catch(() => { setError('Could not load people.'); setLoading(false); }); }, []);
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  const add = async event => { event.preventDefault(); setBusy(true); setError(''); const result = await resources.createOfficer(form); setBusy(false); if (result?.success) { setNotice(`${form.name} is ready to receive work.`); setForm({ name: '', mobile: '', module: 'BOTH', district: 'central', designation: 'Field owner' }); setShowForm(false); load(); } else setError(friendlyError(result?.error)); };
  return <PortalShell role="admin"><PageIntro eyebrow="PEOPLE" title="The people behind the work." detail="Keep the field network current. Owners added here can receive routed complaints." action={<button className="v-button v-button-primary" onClick={() => setShowForm(value => !value)}>{showForm ? 'Close form' : 'Add person'}</button>} />{notice && <div className="v-notice v-notice-success">{notice}</div>}{error && <p className="v-form-error">{error}</p>}{showForm && <form className="v-panel v-form" onSubmit={add} style={{ marginBottom: 18 }}><div className="v-form-grid"><div className="v-field"><label>Name</label><input name="name" value={form.name} onChange={update} required placeholder="Full name" /></div><div className="v-field"><label>Mobile</label><input name="mobile" value={form.mobile} onChange={update} required placeholder="+91 9XXXXXXXXX" /></div><div className="v-field"><label>Workstream</label><select name="module" value={form.module} onChange={update}><option value="BOTH">All civic work</option><option value="DEVELOPMENT">Development</option><option value="WASTE">Waste</option></select></div><div className="v-field"><label>Area</label><select name="district" value={form.district} onChange={update}><option value="central">Central</option><option value="east">East</option><option value="north">North</option><option value="south">South</option><option value="west">West</option></select></div></div><div className="v-form-actions"><button className="v-button v-button-primary" disabled={busy}>{busy ? 'Adding…' : 'Add to people'}</button></div></form>}{loading ? <div className="v-loading" style={{ minHeight: 260 }}><div className="v-loading-mark">N</div></div> : people.length ? <div className="v-people-grid">{people.map(person => <article className="v-person-card" key={person._id}><div className="v-person-avatar">{(person.name || 'P').slice(0, 1).toUpperCase()}</div><div><h3>{person.name}</h3><p>{person.worker_profile?.designation || 'Field owner'}</p><small>{String(person.module || 'BOTH').replace(/_/g, ' ')} · {String(person.ward || 'Central').replace(/_/g, ' ')}</small></div><span className="v-availability"><i />Available</span></article>)}</div> : <EmptyState icon="" title="No people added yet" detail="Add your first field owner to make routing actionable." />}</PortalShell>;
}
