'use client';

import { useEffect, useMemo, useState } from 'react';
import PortalShell from '../../ui/PortalShell';
import { complaints, resources } from '../../lib/api';
import { AssignSelect, EmptyState, PageIntro, friendlyError, readList, readSupervisors } from '../../ui/PortalBlocks';
import { PriorityPill, StatusPill, complaintLocation } from '../../ui/CivicUI';

export default function AdminComplaintsPage() {
  const [items, setItems] = useState([]); const [people, setPeople] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = () => { setLoading(true); Promise.all([complaints.list({ limit: 100 }), resources.supervisors()]).then(([records, owners]) => { setItems(readList(records)); setPeople(readSupervisors(owners)); setError(records?.error || owners?.error || ''); setLoading(false); }).catch(() => { setError('Could not load the routing desk.'); setLoading(false); }); };
  useEffect(() => { load(); }, []);
  useEffect(() => { const focus = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('focus') : ''; if (focus) setSearch(focus); }, []);
  const visible = useMemo(() => items.filter(item => { const matchesSearch = !search || `${item.complaint_id} ${item.complaint_text} ${complaintLocation(item)}`.toLowerCase().includes(search.toLowerCase()); const matchesStatus = status === 'all' || String(item.status).toUpperCase() === status; return matchesSearch && matchesStatus; }), [items, search, status]);
  const assign = async (item, ownerId) => { if (!ownerId) return; setBusy(item._id || item.complaint_id); setError(''); const result = await complaints.assignSupervisor(item._id, ownerId); setBusy(''); if (result?.success) load(); else setError(friendlyError(result?.error)); };
  return <PortalShell role="admin"><PageIntro eyebrow="ROUTING DESK" title="Give every issue an owner." detail="Select a supervisor and the complaint moves into their priority queue immediately." action={<button className="v-button v-button-ghost" onClick={load}>Refresh</button>} /><div className="v-filterbar"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search reference, issue or place" /><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All statuses</option><option value="FILED">Needs routing</option><option value="ASSIGNED">Assigned</option><option value="IN_PROGRESS">In progress</option><option value="AWAITING_VERIFICATION">Awaiting check</option></select><span className="v-result-count">{visible.length} records</span></div>{error && <p className="v-form-error">{error}</p>}{loading ? <div className="v-loading" style={{ minHeight: 300 }}><div className="v-loading-mark">N</div><p>Loading the register</p></div> : visible.length ? <div className="v-table-wrap"><table className="v-table"><thead><tr><th>Complaint</th><th>Priority</th><th>Status</th><th>Supervisor</th></tr></thead><tbody>{visible.map(item => <tr key={item._id || item.complaint_id}><td><strong>{item.complaint_id}</strong><small>{item.complaint_text || 'Civic issue'}</small><small>{complaintLocation(item)}</small></td><td><PriorityPill value={item.priority_score ?? item.priority} /></td><td><StatusPill value={item.status} /></td><td><AssignSelect complaint={item} people={people} busy={busy === (item._id || item.complaint_id)} onAssign={assign} /></td></tr>)}</tbody></table></div> : <EmptyState title="No complaints to route" detail="New submissions will appear here as soon as citizens file them." />}</PortalShell>;
}
