'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import PortalShell from '../../../ui/PortalShell';
import { agents, complaints } from '../../../lib/api';
import CaseStatusRail from '../../../ui/CaseStatusRail';
import { ActivityList, EmptyState, InlineNotice, LoadingState, PageIntro, friendlyError, readComplaint } from '../../../ui/PortalBlocks';
import { PriorityPill, StatusPill, complaintLocation, formatDate, formatRelative, ProgressRail } from '../../../ui/CivicUI';

export default function CitizenComplaintDetail() {
  const { id } = useParams(); const router = useRouter(); const [item, setItem] = useState(null); const [agent, setAgent] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = () => complaints.get(id).then(result => { const complaint = readComplaint(result); setItem(complaint); setError(result?.error || ''); setLoading(false); if (complaint) agents.forComplaint(id).then(agentResult => setAgent(agentResult?.agent || null)).catch(() => null); }).catch(() => { setError('Could not find this complaint.'); setLoading(false); });
  useEffect(() => { load(); }, [id]);
  const verify = async response => { setBusy(true); setError(''); const result = await complaints.citizenVerify(id, response); setBusy(false); if (result?.success) { setNotice(response === 'confirmed' ? 'Thanks - your confirmation closed the loop.' : 'We marked this for follow-up. A supervisor will review it.'); load(); } else setError(friendlyError(result?.error)); };
  if (loading) return <PortalShell role="citizen"><LoadingState /></PortalShell>;
  if (!item) return <PortalShell role="citizen"><EmptyState title="Complaint not found" detail={error || 'This record may have moved.'} action={<button className="v-button v-button-ghost" onClick={() => router.push('/citizen/complaints')}>Back to complaints</button>} /></PortalShell>;
  const needsCheck = ['AWAITING_VERIFICATION', 'PENDING_CLOSURE', 'PROVISIONALLY_CLOSED'].includes(String(item.status).toUpperCase());
  const owner = item.assigned_worker_id?.name || item.assigned_supervisor_id?.name || item.assigned_worker_name || item.assigned_supervisor_name;
  return <PortalShell role="citizen"><PageIntro eyebrow={item.complaint_id || 'COMPLAINT'} title="A clear view of what happens next." detail={`Filed ${formatDate(item.createdAt)} · ${complaintLocation(item)}`} action={<button className="v-button v-button-ghost" onClick={() => router.push('/citizen/complaints')}>All complaints</button>} /><div className="v-detail-grid"><div className="v-panel"><div className="v-detail-title"><div><span className="v-eyebrow">ISSUE</span><h1>{item.complaint_text || 'Civic issue'}</h1><p>{complaintLocation(item)}</p></div><div style={{ display: 'grid', justifyItems: 'end', gap: 8 }}><PriorityPill value={item.priority_score} /><StatusPill value={item.status} /></div></div><ProgressRail status={item.status} />{needsCheck && <InlineNotice tone="warm"><strong>The field team says this is fixed.</strong><span>Confirm it only if the issue is genuinely resolved.</span><div className="v-inline-actions"><button className="v-button v-button-primary" disabled={busy} onClick={() => verify('confirmed')}>Yes, it is fixed</button><button className="v-button v-button-danger" disabled={busy} onClick={() => verify('disputed')}>No, still an issue</button></div></InlineNotice>} {notice && <InlineNotice tone="success">{notice}</InlineNotice>}<div className="v-section-heading"><div><span className="v-eyebrow">TIMELINE</span><h2>What has happened</h2></div></div><ActivityList timeline={item.timeline || []} /></div><aside className="v-detail-aside"><CaseStatusRail agent={agent} complaint={item} /><section className="v-panel"><span className="v-eyebrow">AT A GLANCE</span><div className="v-key-list"><div><span>Reference</span><strong>{item.complaint_id || '-'}</strong></div><div><span>Category</span><strong>{String(item.category || 'Other').replace(/_/g, ' ')}</strong></div><div><span>Assigned owner</span><strong>{owner || 'Being routed'}</strong></div><div><span>Last update</span><strong>{formatRelative(item.updatedAt || item.createdAt)}</strong></div></div>{item.media_urls?.length > 0 && <><div className="v-section-heading" style={{ marginTop: 30 }}><div><span className="v-eyebrow">EVIDENCE</span><h2>Photos</h2></div></div><div className="v-photo-preview">{item.media_urls.map((media, index) => <img src={media.url || media} alt={`Complaint evidence ${index + 1}`} key={`${media.url || media}-${index}`} />)}</div></>}</section></aside></div>{error && <p className="v-form-error">{error}</p>}</PortalShell>;
}
